#!/usr/bin/env python3
# Add a THIRD worksheet ("TypeScript") to "AI price comparison.xlsx" WITHOUT disturbing
# the existing two sheets or their 72 x14 conditional-formatting rules. openpyxl would
# rewrite the whole workbook and strip x14, so we edit the xlsx zip directly:
#   * create xl/worksheets/sheet3.xml (header + one row per model + colour-scale CF)
#   * register it in xl/workbook.xml (<sheet ... r:id="rId6">)
#   * register the relationship in xl/_rels/workbook.xml.rels
#   * register the content-type Override in [Content_Types].xml
# Everything else in the archive is copied verbatim. A timestamped backup is made first.
#
# Aggregates are computed from results-ts.json (local) + results-cloud-ts.json (cloud refs).
# Usage: python3 inject-ts-sheet.py [path-to-xlsx]

import sys, os, re, json, zipfile, shutil, statistics, datetime

DIR = "/sync/Homie/Obsidian/Primary/claudedocs"
XLSX = sys.argv[1] if len(sys.argv) > 1 else os.path.join(DIR, "AI price comparison.xlsx")
HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "..", "results")

# ---- per-model metadata (display name, group, price/1M, CTX). ---------------
# reasoning yes/no is derived empirically from the records, not hardcoded.
META = {
    "nvidia/nemotron-3-nano":                ("Nemotron-3-Nano",      "local", "local", "1M"),
    "openai/gpt-oss-20b":                    ("gpt-oss-20b",          "local", "local", "128k"),
    "mistralai/ministral-3-14b-reasoning":   ("Ministral-3-14B",      "local", "local", "256k"),
    "qwen/qwen3-30b-a3b-2507":               ("Qwen3-30B-A3B-2507",   "local", "local", "256k"),
    "qwen/qwen3-coder-30b":                  ("Qwen3-Coder-30B",      "local", "local", "256k"),
    "qwen/qwen3.6-27b":                      ("Qwen3.6-27B",          "local", "local", "256k"),
    "nvidia_nemotron-cascade-2-30b-a3b":     ("Nemotron-Cascade-30B", "local", "local", "1M"),
    "ornith-1.0-35b":                        ("Ornith-1.0-35B",       "local", "local", "256k"),
    "qwen3.6-35b-a3b-uncensored-heretic-native-mtp-preserved-nvfp4-experts-only":
                                             ("Qwen3.6-35B-Heretic",  "local", "local", "256k"),
    "allenai/olmo-3-32b-think":              ("OLMo-3-32B-Think",     "local", "local", "64k"),
    "bytedance/seed-oss-36b":                ("Seed-OSS-36B",         "local", "local", "512k"),
    "deepseek/deepseek-v3.2":                ("DeepSeek-V3.2",        "ref",   "0.23/0.34", "160k"),
    "anthropic/claude-sonnet-5":             ("Sonnet-5",             "ref",   "2/10",      "1M"),
    # Morph V3 Large: fast-APPLY specialist via morph-client.mjs (folds to single-turn, no tools).
    # Real single-shot tsc+bun numbers; agentic is N/A (no tool-use) -> excluded by the `err` filter.
    "morph/morph-v3-large":                  ("Morph-V3-Large",       "ref",   "0.9/1.9",   "262k"),
    # group "sub" = run through Claude Code headless (`claude -p`, subscription auth). NOT a raw
    # endpoint peer: harness overhead inflates speed/cost, and the agentic tool-loop is N/A (see
    # the "sub"-blanking below and the client's header). Fable 5 also cannot run ZDR.
    "claude-fable-5":                        ("Fable 5 (CC sub)",     "sub",   "sub",       "1M"),
}

# Merge the auto-generated "fast100" cohort metadata (>100 tok/s ZDR sweep [[03.07.2026]]) so the
# TS tab knows their display name / group / price / ctx. Generated by inject-fast100.py.
_fast = os.path.join(RES, "META-fast100.json")
if os.path.exists(_fast):
    for k, v in json.load(open(_fast)).items():
        META.setdefault(k, tuple(v))

def med(xs):
    xs = [x for x in xs if x is not None]
    return round(statistics.median(xs), 1) if xs else None

def load(name):
    p = os.path.join(RES, name)
    return json.load(open(p)) if os.path.exists(p) else []

def aggregate():
    data = (load("results-ts.json") + load("results-cloud-ts.json") + load("results-fable5-ts.json")
            + load("results-morph-ts.json") + load("results-fast100-ts.json"))
    by = {}
    for r in data:
        by.setdefault(r["model"], []).append(r)
    rows = []
    for model, recs in by.items():
        single  = [r for r in recs if r.get("mode") == "single"  and r.get("ok")]
        # `err` marks a run the client refused rather than a real failure (e.g. the Claude Code
        # client rejects agentic tool-loops) — exclude it so A%/toolValid read N/A, not a false 0.
        agentic = [r for r in recs if r.get("mode") == "agentic" and r.get("ok") and not r.get("err")]
        if not single and not agentic:
            continue  # load-failure only -> nothing to report
        name, group, price, ctx = META.get(model, (model, "local", "local", "—"))
        scost = [r.get("cost", 0) for r in single]
        reasoning = "yes" if any((r.get("reasonTok") or 0) > 0 for r in single + agentic) else "no"
        rows.append(dict(
            model=model, name=name, group=group, price=price, ctx=ctx, reasoning=reasoning,
            S=round(100 * sum(r["pct"] for r in single) / len(single)) if single else None,
            full=f"{sum(1 for r in single if r['pct'] >= 0.999)}/{len(single)}" if single else "—",
            typp=round(100 * sum(1 for r in single if r.get("typechecks")) / len(single)) if single else None,
            cost=round(sum(scost) / len(scost), 5) if any(scost) else 0,
            medLat=med([r["latency"] for r in single]),
            medRsn=round(med([r["reasonTok"] for r in single]) or 0),
            A=round(100 * sum(r["pct"] for r in agentic) / len(agentic)) if agentic else None,
            green=f"{sum(1 for r in agentic if r.get('visibleGreen'))}/{len(agentic)}" if agentic else "—",
            toolValid=round(100 * sum(r.get("toolValidPct", 0) for r in agentic) / len(agentic)) if agentic else None,
            recovered=f"{sum(1 for r in agentic if r.get('recovered'))}/{len(agentic)}" if agentic else "—",
            tokps=med([r["tokps"] for r in single if r.get("tokps")]),
            ttft=med([r["ttft"] for r in single if r.get("ttft") is not None]),
        ))
    # group "sub" (Claude Code subscription): blank the harness-inflated / non-comparable columns.
    # Speed (tok/s, TTFT, latency) is dominated by ~46k-token harness prefill; $/task is an
    # API-equivalent, not a real per-token charge; reasoning tokens aren't exposed by `claude -p`.
    # Correctness columns (S%, type%) stay — the objective tsc+bun oracle is robust to this.
    for r in rows:
        if r["group"] == "sub":
            r["cost"] = 0; r["medLat"] = None; r["medRsn"] = None; r["tokps"] = None; r["ttft"] = None

    # local models first, ranked by agentic then single; cloud refs pinned to the bottom.
    locals_ = [r for r in rows if r["group"] == "local"]
    refs = [r for r in rows if r["group"] != "local"]
    locals_.sort(key=lambda r: (-(r["A"] or 0), -(r["S"] or 0)))
    refs.sort(key=lambda r: (-(r["A"] or 0), -(r["S"] or 0)))
    return locals_ + refs

HEADERS = ["Модель", "группа", "цена $ in/out за 1M", "S% (single)", "full-n", "type% (tsc)",
           "$/задача", "medLat, с", "medRsn", "A% (agentic)", "green-n", "toolValid%",
           "recovered-n", "CTX", "reasoning", "tok/s", "TTFT, с"]
# Hover-note documentation attached to each header cell (A1..Q1). Kept concise — one
# sentence explaining what the metric is and how to read it.
HEADER_DOCS = [
    "Идентификатор модели. group=local — из LM Studio (бесплатно, свой GPU); group=ref — облачный якорь (Sonnet 5, DeepSeek-V3.2).",
    "local — локальная модель (LM Studio); ref — облачная референс-модель (OpenRouter, с ценой).",
    "Цена за 1 млн токенов вход/выход, USD. Для локальных — 'local' (бесплатно).",
    "Single-shot: средний % пройденных СКРЫТЫХ тестов (bun test) за 2 прогона × 3 задачи, БЕЗ инструментов. Оракул объективный.",
    "Сколько single-прогонов набрали 100% скрытых тестов из общего числа прогонов.",
    "Доля single-решений, прошедших `tsc --strict` без ошибок типов. Отдельно от корректности: код может работать, но быть типо-несоответствующим (strict:true).",
    "Средняя стоимость одной single-задачи, USD. Только для облачных ref; для локальных пусто.",
    "Медианная задержка single-запроса, секунды (полный ответ).",
    "Медианное число reasoning-токенов на single-задачу (0 = не reasoning-модель).",
    "Agentic: средний % пройденных СКРЫТЫХ тестов в tool-loop (write_lib+run_tests, до 5 шагов). Модель сама итерирует по фидбеку тестов.",
    "Сколько agentic-задач довели видимые тесты до зелёного, из 3.",
    "Fidelity вызова инструментов: доля синтаксически корректных tool-call. <90% = плохо управляет инструментами → непригодна как agentic daily-driver. Родной Qwen-XML восстанавливается fallback-парсером раннера.",
    "Сколько agentic-задач прошли путь red→green (модель увидела провал теста и починила), из 3. Ключевой признак self-repair.",
    "Максимальное окно контекста модели.",
    "Есть ли у модели выделенная reasoning-фаза (reasoning-токены). yes/no.",
    "Медианная скорость генерации, токенов/с (single, фаза декодирования).",
    "Time-to-first-token: медианная задержка до первого токена, секунды. Первый запрос к модели включает JIT-загрузку в LM Studio.",
]
# column -> (header style, data style) reusing indices already present in styles.xml
COLS = "ABCDEFGHIJKLMNOPQ"

def esc(v):
    return str(v).replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")

def cell(ref, style, val, is_num):
    if val is None or val == "":
        return f'<c r="{ref}" s="{style}"/>'
    if is_num:
        return f'<c r="{ref}" s="{style}"><v>{val}</v></c>'
    return f'<c r="{ref}" s="{style}" t="inlineStr"><is><t xml:space="preserve">{esc(val)}</t></is></c>'

def build_sheet(rows, st):
    # st = {hdrA, hdrRest, datA, datRest} — style indices. Detected from the existing
    # sheet3 on refresh (LibreOffice re-saves renumber styles, so hardcoding breaks the
    # tab's look); defaults match sheet1's header/data styles for a first insert.
    hcells = [cell(f"{COLS[i]}1", st["hdrA"] if i == 0 else st["hdrRest"], HEADERS[i], False) for i in range(len(HEADERS))]
    body = [f'<row r="1" ht="30" customHeight="1">' + "".join(hcells) + "</row>"]
    for ri, r in enumerate(rows, start=2):
        vals = [
            (r["name"], False), (r["group"], False), (r["price"], False),
            (r["S"], True), (r["full"], False), (r["typp"], True),
            (r["cost"] if r["cost"] else "", True), (r["medLat"], True), (r["medRsn"], True),
            (r["A"], True), (r["green"], False), (r["toolValid"], True),
            (r["recovered"], False), (r["ctx"], False), (r["reasoning"], False),
            (r["tokps"], True), (r["ttft"], True),
        ]
        cells = []
        for i, (val, is_num) in enumerate(vals):
            style = st["datA"] if i == 0 else st["datRest"]
            cells.append(cell(f"{COLS[i]}{ri}", style, val, is_num))
        body.append(f'<row r="{ri}">' + "".join(cells) + "</row>")
    last = len(rows) + 1

    # 3-colour heatmap (red->yellow->green, 0..50..100) on the % columns D,F,J,L
    def cf(col, prio):
        return (f'<conditionalFormatting sqref="{col}2:{col}{last}">'
                f'<cfRule type="colorScale" priority="{prio}"><colorScale>'
                f'<cfvo type="num" val="0"/><cfvo type="num" val="50"/><cfvo type="num" val="100"/>'
                f'<color rgb="FFF8696B"/><color rgb="FFFFEB84"/><color rgb="FF63BE7B"/>'
                f'</colorScale></cfRule></conditionalFormatting>')
    cfs = cf("D", 1) + cf("F", 2) + cf("J", 3) + cf("L", 4)

    widths = ('<cols>'
              '<col min="1" max="1" width="24" customWidth="1"/>'
              '<col min="2" max="2" width="8" customWidth="1"/>'
              '<col min="3" max="3" width="16" customWidth="1"/>'
              '<col min="4" max="17" width="11" customWidth="1"/>'
              '</cols>')
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
        'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        f'<dimension ref="A1:Q{last}"/>'
        '<sheetViews><sheetView workbookViewId="0">'
        '<pane xSplit="1" ySplit="1" topLeftCell="B2" activePane="bottomRight" state="frozen"/>'
        '</sheetView></sheetViews>'
        '<sheetFormatPr defaultRowHeight="15"/>'
        f'{widths}'
        f'<sheetData>{"".join(body)}</sheetData>'
        f'{cfs}'
        '<legacyDrawing r:id="rId2"/>'   # links header-cell comments (via vmlDrawing3)
        '</worksheet>'
    )

# ---- header-cell hover comments (legacy VML notes, mirroring comments1.xml) ----
def build_comments():
    items = []
    for i, doc in enumerate(HEADER_DOCS):
        ref = f"{COLS[i]}1"
        items.append(
            f'<comment ref="{ref}" authorId="0"><text><r>'
            f'<rPr><sz val="10"/><rFont val="Arial"/><family val="2"/></rPr>'
            f'<t xml:space="preserve">{esc(doc)}</t></r></text></comment>'
        )
    return ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
            '<comments xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
            '<authors><author>bench</author></authors>'
            f'<commentList>{"".join(items)}</commentList></comments>')

def build_vml():
    shapes = []
    for i in range(len(HEADER_DOCS)):
        # anchor the (hidden) note box a couple columns to the right of its header cell
        anchor = f"{i+1},15,1,2,{i+4},15,7,4"
        shapes.append(
            f'<v:shape id="hdrnote{i}" type="#_x0000_t202" fillcolor="#ffffe1" o:insetmode="auto" '
            f'style="position:absolute;margin-left:100pt;margin-top:2pt;width:220pt;height:90pt;'
            f'mso-wrap-style:none;v-text-anchor:middle;visibility:hidden">'
            f'<v:fill color2="#ffffe1"/><v:shadow on="t" color="black" obscured="t"/>'
            f'<v:path o:connecttype="none"/>'
            f'<v:textbox style="mso-direction-alt:auto"><div style="text-align:left"></div></v:textbox>'
            f'<x:ClientData ObjectType="Note"><x:MoveWithCells/><x:SizeWithCells/>'
            f'<x:Anchor>{anchor}</x:Anchor><x:AutoFill>False</x:AutoFill>'
            f'<x:Row>0</x:Row><x:Column>{i}</x:Column></x:ClientData></v:shape>'
        )
    return ('<xml xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" '
            'xmlns:x="urn:schemas-microsoft-com:office:excel">'
            '<o:shapelayout v:ext="edit"><o:idmap v:ext="edit" data="3"/></o:shapelayout>'
            '<v:shapetype id="_x0000_t202" coordsize="21600,21600" o:spt="202" '
            'path="m,l,21600l21600,21600l21600,xe"><v:stroke joinstyle="miter"/>'
            '<v:path gradientshapeok="t" o:connecttype="rect"/></v:shapetype>'
            f'{"".join(shapes)}</xml>')

SHEET3_RELS = ('<?xml version="1.0" encoding="UTF-8"?>\n'
               '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
               '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="../comments3.xml"/>'
               '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/vmlDrawing" Target="../drawings/vmlDrawing3.vml"/>'
               '</Relationships>')

def patch_workbook(xml):
    # add a third <sheet> right before </sheets>
    tag = '<sheet name="TypeScript" sheetId="3" state="visible" r:id="rId6"/>'
    return xml.replace("</sheets>", tag + "</sheets>", 1)

def patch_rels(xml):
    rel = ('<Relationship Id="rId6" '
           'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" '
           'Target="worksheets/sheet3.xml"/>')
    return xml.replace("</Relationships>", rel + "</Relationships>", 1)

def patch_ctypes(xml):
    # Add only the Overrides that aren't already present (idempotent across re-runs).
    wanted = [
        ("/xl/worksheets/sheet3.xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"),
        ("/xl/comments3.xml", "application/vnd.openxmlformats-officedocument.spreadsheetml.comments+xml"),
        ("/xl/drawings/vmlDrawing3.vml", "application/vnd.openxmlformats-officedocument.vmlDrawing"),
    ]
    adds = "".join(f'<Override PartName="{p}" ContentType="{c}"/>' for p, c in wanted if p not in xml)
    return xml.replace("</Types>", adds + "</Types>", 1) if adds else xml

def detect_styles(xml):
    """Read the style index of A1/B1 (header) and A2/B2 (data) from an existing sheet3,
    so a refresh matches whatever the last writer (incl. LibreOffice re-save) settled on."""
    def s_of(ref):
        m = re.search(rf'<c r="{ref}"[^>]*\bs="(\d+)"', xml)
        return int(m.group(1)) if m else None
    defaults = {"hdrA": 6, "hdrRest": 7, "datA": 13, "datRest": 9}
    found = {"hdrA": s_of("A1"), "hdrRest": s_of("B1"), "datA": s_of("A2"), "datRest": s_of("B2")}
    return {k: (found[k] if found[k] is not None else defaults[k]) for k in defaults}


def main():
    rows = aggregate()
    if not rows:
        print("No TS results found — aborting.")
        return

    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M")
    shutil.copy2(XLSX, f"{XLSX}.bak-ts-{stamp}")

    tmp = XLSX + ".tmp"
    zin = zipfile.ZipFile(XLSX, "r")
    names = set(zin.namelist())
    exists = "xl/worksheets/sheet3.xml" in names
    # style indices: detect from the current sheet3 on refresh, else sheet1-header defaults
    st = detect_styles(zin.read("xl/worksheets/sheet3.xml").decode("utf-8")) if exists \
        else {"hdrA": 6, "hdrRest": 7, "datA": 13, "datRest": 9}
    sheet3 = build_sheet(rows, st)
    # Parts we always (re)write — the sheet plus its header-comment infrastructure.
    new_parts = {
        "xl/worksheets/sheet3.xml": sheet3.encode("utf-8"),
        "xl/comments3.xml": build_comments().encode("utf-8"),
        "xl/drawings/vmlDrawing3.vml": build_vml().encode("utf-8"),
        "xl/worksheets/_rels/sheet3.xml.rels": SHEET3_RELS.encode("utf-8"),
    }
    # Content-types are patched idempotently (adds only missing Overrides).
    repl = {"[Content_Types].xml": patch_ctypes(zin.read("[Content_Types].xml").decode("utf-8")).encode("utf-8")}
    if not exists:                           # register the sheet in workbook + rels (once)
        repl["xl/workbook.xml"] = patch_workbook(zin.read("xl/workbook.xml").decode("utf-8")).encode("utf-8")
        repl["xl/_rels/workbook.xml.rels"] = patch_rels(zin.read("xl/_rels/workbook.xml.rels").decode("utf-8")).encode("utf-8")
    # Existing parts are replaced in-loop; brand-new parts are appended after.
    for name, data in new_parts.items():
        if name in names:
            repl[name] = data
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            zout.writestr(item, repl.get(item.filename, zin.read(item.filename)))
        for name, data in new_parts.items():
            if name not in names:
                zout.writestr(name, data)
    zin.close()
    shutil.move(tmp, XLSX)

    verb = "Refreshed" if exists else "Added"
    print(f"{verb} 'TypeScript' sheet with {len(rows)} model rows. Backup: {XLSX}.bak-ts-{stamp}")
    for r in rows:
        print(f"  {r['name']:22} grp={r['group']:5} S={r['S']} type={r['typp']} A={r['A']} tool={r['toolValid']} rec={r['recovered']}")

if __name__ == "__main__":
    main()
